version: '3'

services:
  app:
    build: .
    ports:
      - 8000:80
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
      DATABASE_NAME: cycly
      DEBUG: 1
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /app
    restart: on-failure


  database:
    image: mysql:8.1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cycly

volumes:
  mysql-data:
