version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DB: cycly

  database:
    image: postgres:16-bookworm
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cycly

volumes:
  postgres-data:
